services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=posts'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=syn'
      - 'POSTGRES_HOST_AUTH_METHOD=password'
    ports:
      - '5432:5432'